# Generated by Django 5.1.7 on 2025-03-24 17:21

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('feed', '0003_comment_like_alter_post_options_remove_post_likes_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'post', 'interaction_type')},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user is verified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last time the user was active'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media links in JSON format'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional interaction data'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about yourself (max 500 chars)', max_length=500, null=True, validators=[users.models.validate_bio_length]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to=users.models.upload_to_profile_pics, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('VIEW', 'View'), ('SHARE', 'Share'), ('FOLLOW', 'Follow'), ('BOOKMARK', 'Bookmark')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to='feed.post'),
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'post', 'interaction_type'), ('user', 'target_user', 'interaction_type')},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='users_custo_usernam_a8ad03_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_seen'], name='users_custo_last_se_bff179_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['code'], name='users_invit_code_807843_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['created_at'], name='users_invit_created_cd0b28_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='users_messa_sender__b9036c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='users_messa_created_67ebe9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='users_messa_is_read_0a8982_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='users_useri_user_id_b1dcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['timestamp'], name='users_useri_timesta_390cf1_idx'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
