# Generated by Django 5.1.7 on 2025-03-24 14:02

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
        ('users', '0002_customuser_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='invitecode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invite Code', 'verbose_name_plural': 'Invite Codes'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Private Message', 'verbose_name_plural': 'Private Messages'},
        ),
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Interaction', 'verbose_name_plural': 'User Interactions'},
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'post', 'interaction_type')},
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('VIEW', 'View'), ('SHARE', 'Share')], default='VIEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about yourself', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Users this user is following', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='used_invite',
            field=models.BooleanField(default=False, help_text='Has this user used an invite code?'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=users.models.generate_invite_code, help_text='Unique invite code', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this invite', on_delete=django.db.models.deletion.CASCADE, related_name='generated_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='used_by',
            field=models.OneToOneField(blank=True, help_text='User who redeemed this invite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='feed.post'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='commented',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='viewed',
        ),
    ]
