# Generated by Django 5.1.7 on 2025-03-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
