# Generated by Django 5.1.7 on 2025-03-24 14:11

from django.db import migrations

def migrate_user_interactions(apps, schema_editor):
    UserInteraction = apps.get_model('users', 'UserInteraction')
    
    # Iterate through the existing UserInteraction records
    for interaction in UserInteraction.objects.all():
        if interaction.liked:
            interaction.interaction_type = 'LIKE'
        elif interaction.commented:
            interaction.interaction_type = 'COMMENT'
        elif interaction.viewed:
            interaction.interaction_type = 'VIEW'
        interaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_invitecode_options_and_more.py'),
    ]

    operations = [
        migrations.RunPython(migrate_user_interactions),
    ]
