# Generated by Django 5.1.7 on 2025-03-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
