# Generated by Django 5.1.7 on 2025-03-19 13:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_invite_code_invitecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=users.models.generate_invite_code, max_length=10, unique=True),
        ),
    ]
