# Generated by Django 5.1.7 on 2025-03-20 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_invitecode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='used_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to='users.post'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
